name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: cv-downloader
        path: |
          ./target/release/cv_downloader
          ./target/release/cv_downloader.exe
        retention-days: 90
